apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cns-website
spec:
  replicas: 2
  selector:
    matchLabels:
      run:  cns-website
  template:
    metadata:
      labels:
        run:  cns-website
    spec:
      containers:
      - name: cns-website
        image: docker.io/anaisurlichs/cns-website@sha256:c5911ac313e0be82a740bd726dc290e655800a9588424ba4e0558c705d1287fd
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: dockerconfigjson-github-com