apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cns-website
spec:
  replicas: 2
  selector:
    matchLabels:
      run:  cns-website
  template:
    metadata:
      labels:
        run:  cns-website
    spec:
      containers:
      - name: cns-website
        image: ghcr.io/cloud-native-security/secret-repo:0.0.9
        ports:
          - containerPort: 80
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: dockerconfigjson-github-com