name: Create Cluster
on:
  push:
    branches:
    - main
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        with:
          version: 'v0.20.0'
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - 
        name: Run chart-testing (install)
        run: helm install website cns-website 
      - 
        name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'k8s'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          trivy-config: trivy.yaml
      - 
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - 
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: get all -n default
  